pipeline {
    agent any

    tools {
        maven 'maven'
    }

    stages {
        stage('Build & SonarQube analysis') {
            steps {
              withSonarQubeEnv(installationName: 'SonarQube') { 
              sh 'mvn -f calculadora-api/pom.xml clean package sonar:sonar'
            }
          }
        }
        stage('Quality gate') {
            steps {
              waitForQualityGate abortPipeline: true
            }
          }
    }
}